/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'Blinky.Debug+BlackPill' 
 * Target:  'Debug+BlackPill' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::CMSIS Driver:GPIO@1.2.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* WeActStudio::CMSIS Driver:VIO:Board@1.0.0 */
#define RTE_VIO_BOARD


#endif /* RTE_COMPONENTS_H */
