/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'RangeFinder.Debug+BlackPill' 
 * Target:  'Debug+BlackPill' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::CMSIS Driver:GPIO@1.2.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS Driver:I2C@3.0.0 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */
#define RTE_Drivers_I2C3                /* Driver I2C3 */
#define RTE_Drivers_I2C4                /* Driver I2C4 */
#define RTE_Drivers_I2C5                /* Driver I2C5 */
#define RTE_Drivers_I2C6                /* Driver I2C6 */
#define RTE_Drivers_I2C7                /* Driver I2C7 */
#define RTE_Drivers_I2C8                /* Driver I2C8 */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* WeActStudio::CMSIS Driver:VIO:Board@1.0.0 */
#define RTE_VIO_BOARD


#endif /* RTE_COMPONENTS_H */
