/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'RangeFinder.Debug+BlackPill' 
 * Target:  'Debug+BlackPill' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:GPIO@1.2.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS Driver:I2C@3.0.0 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */
#define RTE_Drivers_I2C3                /* Driver I2C3 */
#define RTE_Drivers_I2C4                /* Driver I2C4 */
#define RTE_Drivers_I2C5                /* Driver I2C5 */
#define RTE_Drivers_I2C6                /* Driver I2C6 */
#define RTE_Drivers_I2C7                /* Driver I2C7 */
#define RTE_Drivers_I2C8                /* Driver I2C8 */
/* Keil::CMSIS Driver:USB Device@3.1.0 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
#define RTE_Drivers_USBD1               /* Driver USBD1 */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:CDC@8.0.0 */
#define RTE_USB_Device_CDC_0            /* USB Device CDC instance 0 */

/* Keil::USB&MDK:Device@8.0.0 */
#define RTE_USB_Device_0                /* USB Device 0 */

/* WeActStudio::CMSIS Driver:VIO:Board@1.0.0 */
#define RTE_VIO_BOARD


#endif /* RTE_COMPONENTS_H */
